# Generated by Django 5.2.17 on 2026-10-03 11:09

import core.models
import core.validators
import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('text', models.CharField(max_length=300)),
                ('at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to=core.models.p_blog, validators=[core.validators.validate_image])),
                ('excerpt', models.CharField(max_length=300, verbose_name='One-line description')),
                ('content', models.TextField(help_text="Blank line = new paragraph. '## ' = heading. '- ' = list item.")),
                ('author', models.CharField(default='[BLOG_AUTHOR]', max_length=120)),
                ('category', models.CharField(default='[BLOG_CATEGORY]', max_length=80)),
                ('published_at', models.DateField(default=datetime.date.today, verbose_name='Publication date')),
                ('reading_time', models.PositiveIntegerField(default=0, help_text='0 = calculate automatically', verbose_name='Reading time (min)')),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200, verbose_name='Issuing organization')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=120)),
                ('credential_url', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, upload_to=core.models.p_cert_img, validators=[core.validators.validate_image], verbose_name='Preview image')),
                ('pdf', models.FileField(blank=True, upload_to=core.models.p_cert_pdf, validators=[core.validators.validate_pdf], verbose_name='PDF')),
                ('description', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', '-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('field', models.CharField(blank=True, max_length=200, verbose_name='Field of study')),
                ('start_year', models.CharField(blank=True, max_length=12)),
                ('end_year', models.CharField(blank=True, help_text="Year or 'Present'", max_length=12)),
                ('grade', models.CharField(blank=True, max_length=80)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to=core.models.p_edu, validators=[core.validators.validate_image], verbose_name='Image / logo')),
            ],
            options={
                'verbose_name_plural': 'education',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JourneyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=core.models.p_journey, validators=[core.validators.validate_image])),
                ('category', models.CharField(choices=[('education', 'Education'), ('internship', 'Internship'), ('project', 'Project'), ('event', 'Event'), ('hackathon', 'Hackathon'), ('achievement', 'Achievement'), ('certification', 'Certification'), ('activity', 'Activity'), ('other', 'Other')], default='other', max_length=20)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('link', models.CharField(blank=True, max_length=300, verbose_name='External link')),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'journey entries',
                'ordering': ['order', '-date'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.p_library)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='[PERSON_NAME]', max_length=120)),
                ('title', models.CharField(default='[PROFESSIONAL_TITLE]', max_length=160, verbose_name='Professional title')),
                ('tagline', models.CharField(blank=True, default='[SHORT_TAGLINE]', max_length=240)),
                ('intro', models.TextField(blank=True, default='[SHORT_INTRODUCTION]', verbose_name='Short introduction')),
                ('about', models.TextField(blank=True, default='[ABOUT_DESCRIPTION]', verbose_name='About description')),
                ('focus', models.CharField(blank=True, default='[PROFESSIONAL_FOCUS]', max_length=240, verbose_name='Professional focus')),
                ('interests', models.CharField(blank=True, default='[INTERESTS]', help_text='Comma separated', max_length=240)),
                ('email', models.CharField(blank=True, default='[EMAIL_ADDRESS]', max_length=160)),
                ('phone', models.CharField(blank=True, default='[PHONE_NUMBER]', max_length=60)),
                ('location', models.CharField(blank=True, default='[LOCATION]', max_length=160)),
                ('image', models.ImageField(blank=True, upload_to=core.models.p_profile, validators=[core.validators.validate_image], verbose_name='Profile image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to=core.models.p_proj, validators=[core.validators.validate_image])),
                ('short_description', models.CharField(max_length=240, verbose_name='One-line description')),
                ('full_description', models.TextField(blank=True, verbose_name='Overview')),
                ('technologies', models.CharField(blank=True, help_text='Comma separated', max_length=400)),
                ('problem', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('features', models.TextField(blank=True, help_text='One feature per line')),
                ('implementation', models.TextField(blank=True)),
                ('github_url', models.CharField(blank=True, max_length=300, verbose_name='GitHub URL')),
                ('live_url', models.CharField(blank=True, max_length=300, verbose_name='Live URL')),
                ('year', models.CharField(blank=True, max_length=12)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='[RESUME_TITLE]', max_length=160)),
                ('version', models.CharField(blank=True, default='v1', max_length=40)),
                ('pdf', models.FileField(upload_to=core.models.p_resume_pdf, validators=[core.validators.validate_pdf], verbose_name='Resume PDF')),
                ('preview_image', models.ImageField(blank=True, upload_to=core.models.p_resume_img, validators=[core.validators.validate_image])),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='[SITE_NAME]', max_length=120)),
                ('description', models.CharField(blank=True, default='[SITE_DESCRIPTION]', max_length=300)),
                ('seo_title', models.CharField(blank=True, default='[SEO_TITLE]', max_length=160, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, default='[SEO_DESCRIPTION]', max_length=300, verbose_name='SEO description')),
                ('favicon', models.ImageField(blank=True, upload_to=core.models.p_site, validators=[core.validators.validate_image])),
                ('og_image', models.ImageField(blank=True, upload_to=core.models.p_site, validators=[core.validators.validate_image], verbose_name='Open Graph image')),
                ('footer_text', models.CharField(blank=True, default='[FOOTER_TEXT]', max_length=300)),
                ('primary_email', models.CharField(blank=True, default='[EMAIL_ADDRESS]', help_text='Shown in the footer.', max_length=160)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('languages', 'Languages'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('databases', 'Databases'), ('ai_ml', 'AI / ML'), ('cloud', 'Cloud'), ('devops', 'DevOps'), ('tools', 'Tools'), ('other', 'Other')], default='other', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Optional short text/emoji', max_length=40)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('label', models.CharField(help_text='e.g. GitHub, LinkedIn', max_length=60)),
                ('url', models.CharField(max_length=300, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.p_shot, validators=[core.validators.validate_image])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
