# Generated by Django 5.2.17 on 2026-10-04 05:44

from django.db import migrations, models

LABELS = {"languages": "Languages", "tools": "Tools", "other": "Other"}


def slugs_to_labels(apps, schema_editor):
    Skill = apps.get_model("core", "Skill")
    for old, new in LABELS.items():
        Skill.objects.filter(category=old).update(category=new)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="category",
            field=models.CharField(
                default="Other",
                help_text="Pick an existing category or type a new one.",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="icon",
            field=models.CharField(
                blank=True, help_text="Optional short text/ icon", max_length=40
            ),
        ),
        migrations.RunPython(slugs_to_labels, migrations.RunPython.noop),
    ]
