# Generated by Django 5.2.17 on 2026-10-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_skill_free_text_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="description",
            field=models.CharField(blank=True, default="Portfolio", max_length=300),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="footer_text",
            field=models.CharField(
                blank=True,
                default="© 2026 Antony Roshan. All rights reserved.",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="seo_description",
            field=models.CharField(
                blank=True,
                default="Personal Portfolio",
                max_length=300,
                verbose_name="SEO description",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="seo_title",
            field=models.CharField(
                blank=True,
                default="Antony Roshan",
                max_length=160,
                verbose_name="SEO title",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_name",
            field=models.CharField(default="Antony Roshan", max_length=120),
        ),
    ]
