# Generated by Django 5.2.17 on 2026-10-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_sitesettings_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="author",
            field=models.CharField(default="Antony Roshan", max_length=120),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="category",
            field=models.CharField(default="General", max_length=80),
        ),
    ]
